# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-06 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanager',
            name='login_password',
            field=models.CharField(help_text='Password should have at least one lower and upper case letter, at least one number and one special character(e.g. !?.@#$).', max_length=128, verbose_name='Login password'),
        ),
    ]
