# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-19 13:31
from __future__ import unicode_literals

import apps.search_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=apps.search_app.models.upload_path)),
                ('url_source', models.URLField(max_length=128)),
                ('url_name', models.CharField(choices=[('auth_chat', 'auth_chat'), ('change_styling', 'change_styling'), ('codility', 'codility'), ('julia_set', 'julia_set'), ('mpl_graph', 'mpl_graph'), ('scikit_chart', 'scikit_chart'), ('search_app', 'search_app'), ('tree_traversal', 'tree_traversal'), ('wallpaper', 'wallpaper')], max_length=128, unique=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Applications',
                'verbose_name_plural': 'Applications',
                'ordering': ('?',),
            },
        ),
    ]
