# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='url_name',
            field=models.CharField(choices=[('auth_chat', 'auth_chat'), ('change_styling', 'change_styling'), ('codility', 'codility'), ('julia_set', 'julia_set'), ('mpl_graph', 'mpl_graph'), ('password_manager', 'password_manager'), ('scikit_chart', 'scikit_chart'), ('search_app', 'search_app'), ('tree_traversal', 'tree_traversal'), ('wallpaper', 'wallpaper')], max_length=128, unique=True),
        ),
    ]
